#Guessing Game
#Guess what number has been generated by the computer

import os
import random
from msvcrt import getch

def initial_setup():
    os.system('cls')
    print("\n") #dla czytelnosci
    print("Welcome to the Guessing Game!")
    print("You need to guess which number what randomly generated by the computer.")
    print("Press Enter to start the game, or Escape to quit.")
    while(True):
        key_pressed= ord(getch())
        if key_pressed == 13: #enter
            return
        elif key_pressed == 27: #escape
            quit()
    
def calculate_input():
    generated_number = random.randint(1,9)
    amount_of_guesses = 0
    
    print("\nGuess which number was generated!")
    while (True):
        player_guess = int(input("Your guess: "))
        if player_guess == "exit": quit()
        amount_of_guesses += 1
        if player_guess == generated_number: print("That is correct!!!"); break
        elif player_guess < generated_number: print("Your guess is to low!")
        else: print("Your guess is too high!")
    print("Amount of tries: " + str(amount_of_guesses) + "\n")
    return
 
def quit_or_play():
    print("Press Enter to play again, or Escape to quit...")
    while(True):
        play_again = ord(getch())
        if play_again == 27:
            quit()
        elif play_again == 13:
            break
            
def main():
    while(True): 
        initial_setup()
        calculate_input()
        quit_or_play()

main()